apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: volsync--actual--actual-dst
  namespace: dotfiles
spec:
  restic:
    copyMethod: Direct
    destinationPVC: actual
    moverSecurityContext:
      runAsGroup: 101
      runAsUser: 101
    repository: volsync--actual--actual
  trigger:
    manual: "1"
