apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak
  namespace: security
spec:
  data:
    - remoteRef:
        key: keycloak
      secretKey: superadmin
  dataFrom:
    - extract:
        key: keycloak.main.credentials.postgresql.acid.zalan.do
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-default
  target:
    template:
      data:
        db-password: '{{ .password }}'
        superadmin: '{{ .superadmin }}'
