apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-crossplane
  namespace: security
spec:
  data:
    - remoteRef:
        key: keycloak/superadmin
      secretKey: superadmin
    - remoteRef:
        key: keycloak/tristan
      secretKey: tristan
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    template:
      data:
        client_id: admin-cli
        password: '{{ .superadmin }}'
        tristan: '{{ .tristan }}'
        url: https://keycloak.trdos.me
        username: superadmin
