apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
  name: keycloak
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: metrics
      scheme: http
    - interval: 30s
      path: /realms/admin/metrics
      port: http
      scheme: http
  namespaceSelector:
    matchNames:
      - security
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
      app.kubernetes.io/instance: keycloak
      app.kubernetes.io/name: keycloak
