keys:
  - &tristan age198yu3najdv79x087fa9qnl9x0pctugcl08ccc3cjpxd6h8ygp57sjglj0k
creation_rules:
  - path_regex: src/dev/sops/default.yaml$
    key_groups:
      - age:
          - *tristan
  - path_regex: src/dev/sops/tristan$
    key_groups:
      - age:
          - *tristan
