apiVersion: v1
kind: Pod
metadata:
  annotations:
    helm.sh/hook: test
  labels:
    app.kubernetes.io/instance: kubelet-csr-approver
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubelet-csr-approver
  name: kubelet-csr-approver-test-connection
  namespace: security
spec:
  containers:
    - command:
        - /bin/sh
        - -c
        - |
          sleep 10 ; wget -O- -S kubelet-csr-approver:8080/metrics
      image: busybox
      name: wget
  restartPolicy: Never
