apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: kubelet-csr-approver
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubelet-csr-approver
  name: kubelet-csr-approver
  namespace: security
spec:
  endpoints:
    - interval: 1m
      path: /metrics
      port: metrics
      scheme: http
      scrapeTimeout: 10s
  jobLabel: kubelet-csr-approver
  namespaceSelector:
    matchNames:
      - security
  selector:
    matchLabels:
      app.kubernetes.io/instance: kubelet-csr-approver
      app.kubernetes.io/name: kubelet-csr-approver
