apiVersion: v1
data:
  HARDCOVER_AUTH_FILE: /secrets/hardcover_token.txt
  POSTGRES_HOST: main.default.svc.cluster.local
  POSTGRES_PASSWORD_FILE: /secrets/db_password.txt
  POSTGRES_USER: rreading-glasses
  UPSTREAM: readarr.media.svc.cluster.local
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: readarr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: readarr
  name: readarr-rreading-glasses
  namespace: dotfiles
