apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rreading-glasses
  namespace: dotfiles
spec:
  data:
    - remoteRef:
        key: hardcover
      secretKey: hardcover_token.txt
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: rreading-glasses.main.credentials.postgresql.acid.zalan.do
        property: password
      secretKey: db_password.txt
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-default
