apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: volsync--readarr--readarr-src
  namespace: dotfiles
spec:
  restic:
    copyMethod: Direct
    moverSecurityContext:
      fsGroup: 101
    pruneIntervalDays: 8
    repository: volsync--readarr--readarr
    retain:
      daily: 1
      monthly: 1
      weekly: 1
      yearly: 1
  sourcePVC: readarr
  trigger:
    schedule: 0 4 * * *
