apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: reloader
    meta.helm.sh/release-namespace: cicd
  labels:
    app: reloader-reloader
    app.kubernetes.io/managed-by: Helm
    chart: reloader-2.0.0
    heritage: Helm
    release: reloader
  name: reloader-reloader-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: reloader-reloader-role
subjects:
  - kind: ServiceAccount
    name: reloader-reloader
    namespace: cicd
