apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    meta.helm.sh/release-name: reloader
    meta.helm.sh/release-namespace: cicd
  labels:
    app: reloader-reloader
    app.kubernetes.io/managed-by: Helm
    chart: reloader-2.0.0
    group: com.stakater.platform
    heritage: Helm
    provider: stakater
    release: reloader
    version: v1.3.0
  name: reloader-reloader
  namespace: cicd
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: reloader-reloader
      release: reloader
  template:
    metadata:
      labels:
        app: reloader-reloader
        app.kubernetes.io/managed-by: Helm
        chart: reloader-2.0.0
        group: com.stakater.platform
        heritage: Helm
        provider: stakater
        release: reloader
        version: v1.3.0
    spec:
      containers:
        - args:
            - --log-level=info
          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  divisor: "1"
                  resource: limits.cpu
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  divisor: "1"
                  resource: limits.memory
          image: ghcr.io/stakater/reloader:v1.3.0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /live
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: reloader-reloader
          ports:
            - containerPort: 9090
              name: http
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /metrics
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          securityContext: {}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: reloader-reloader
