apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: reloader
    meta.helm.sh/release-namespace: cicd
  labels:
    app: reloader-reloader
    app.kubernetes.io/managed-by: Helm
    chart: reloader-2.0.0
    heritage: Helm
    release: reloader
  name: reloader-reloader
  namespace: cicd
