apiVersion: v1
data:
  nfd-worker.conf: |-
    core:
      sources:
      - pci
      - system
      - usb
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: node-feature-discovery
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: node-feature-discovery
  name: node-feature-discovery-worker-conf
  namespace: kube-system
