apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo
  namespace: dotfiles
spec:
  data:
    - remoteRef:
        key: keycloak/clients/forgejo
      secretKey: '{{ .keycloak }}'
    - remoteRef:
        key: forgejo.main.credentials.postgresql.acid.zalan.do
        property: password
      secretKey: postgres
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-default
    - remoteRef:
        key: dragonflydb/forgejo
      secretKey: dragonfly
    - remoteRef:
        key: forgejo
      secretKey: admin
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    template:
      data:
        DRAGONFLY_PASSWORD: '{{ .dragonfly }}'
        FORGEJO__cache__HOST: redis://:{{ .dragonfly }}@forgejo-dragonfly.dotfiles.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s
        FORGEJO__database__PASSWD: '{{ .postgres }}'
        FORGEJO__queue__CONN_STR: redis://:{{ .dragonfly }}@forgejo-dragonfly.dotfiles.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s
        FORGEJO__session__PROVIDER_CONFIG: redis://:{{ .dragonfly }}@forgejo-dragonfly.dotfiles.svc.cluster.local:6379/0?pool_size=100&idle_timeout=180s
        GITEA_ADMIN_PASSWORD: '{{ .admin }}'
        GITEA_OAUTH_SECRET_0: '{{ .keycloak }}'
