apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: forgejo
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: forgejo
  name: forgejo-config
  namespace: dotfiles
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
