apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: volsync--forgejo--forgejo-dst
  namespace: dotfiles
spec:
  restic:
    copyMethod: Direct
    destinationPVC: gitea-shared-storage
    moverSecurityContext:
      runAsGroup: 101
      runAsUser: 101
    repository: volsync--forgejo--forgejo
  trigger:
    manual: "1"
