apiVersion: v1
kind: Service
metadata:
  name: windmill-app
  namespace: dotfiles
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app.kubernetes.io/name: windmill-app
  sessionAffinity: ClientIP
  type: ClusterIP
