apiVersion: v1
kind: Service
metadata:
  labels:
    operated-prometheus: "true"
  name: windmill-mcp-metrics
  namespace: dotfiles
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 8001
      protocol: TCP
  selector:
    app.kubernetes.io/name: windmill-mcp
  sessionAffinity: None
  type: ClusterIP
