# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!
{fetchNuGet}: [
  (fetchNuGet {
    pname = "Autofac";
    version = "8.0.0";
    hash = "sha256-7XhDXw8hatQFjQMTIorQ5XrfDCc7EVNVyi6bGbc5fnA=";
  })
  (fetchNuGet {
    pname = "Avalonia";
    version = "11.0.10";
    hash = "sha256-FuGl5admJ9AeRNrg/faGfqx8pwxGxdkmbnth9Jxhelc=";
  })
  (fetchNuGet {
    pname = "Avalonia.Angle.Windows.Natives";
    version = "2.1.0.2023020321";
    hash = "sha256-TWop9cvak6cMv2vrA/GlpuYBxS8Fuj5UmupGIV7Q5Ks=";
  })
  (fetchNuGet {
    pname = "Avalonia.BuildServices";
    version = "0.0.29";
    hash = "sha256-WPHRMNowRnYSCh88DWNBCltWsLPyOfzXGzBqLYE7tRY=";
  })
  (fetchNuGet {
    pname = "Avalonia.Controls.ColorPicker";
    version = "11.0.10";
    hash = "sha256-G0ooIjNRW5YHKvQ6qPxe5gaE3HPwGfiCQUo34PSxXGg=";
  })
  (fetchNuGet {
    pname = "Avalonia.Controls.DataGrid";
    version = "11.0.10";
    hash = "sha256-0v4evkV0jbLffwfQG/QO/RQbHXlCBmFv8A2pBZjS5Y0=";
  })
  (fetchNuGet {
    pname = "Avalonia.Desktop";
    version = "11.0.10";
    hash = "sha256-fIty7TfiTC+OX9gCH4tA8Fs9dF4+G7Mhs9XnZadUR2g=";
  })
  (fetchNuGet {
    pname = "Avalonia.Diagnostics";
    version = "11.0.10";
    hash = "sha256-itnN+LIZ2S+1CjD0ZS/woKtpgWbC/srMYzbYfX3a8LA=";
  })
  (fetchNuGet {
    pname = "Avalonia.FreeDesktop";
    version = "11.0.10";
    hash = "sha256-uVNOOVTQIqQ2pDgSsz5saI7+fMvps40vJlMp1/XdyaE=";
  })
  (fetchNuGet {
    pname = "Avalonia.Native";
    version = "11.0.10";
    hash = "sha256-P9j01FDXDpixo8wBVH3XK0Am6UBhG52HDrzt1ZqD8Ro=";
  })
  (fetchNuGet {
    pname = "Avalonia.Remote.Protocol";
    version = "11.0.10";
    hash = "sha256-qtvlczTg2yUZWyyqXkkboB8lK9aYv+STbfDvSKb55Vw=";
  })
  (fetchNuGet {
    pname = "Avalonia.Skia";
    version = "11.0.10";
    hash = "sha256-1SU17j43Fiw4LbEEgqx10zE/iIVPfb8G1JVbfD2RhXA=";
  })
  (fetchNuGet {
    pname = "Avalonia.Themes.Simple";
    version = "11.0.10";
    hash = "sha256-54fc2g1yvM7pPRaF062lSjXaQDe2i61xQRM8m81vWm8=";
  })
  (fetchNuGet {
    pname = "Avalonia.Win32";
    version = "11.0.10";
    hash = "sha256-+o228ElrBJBxBkZKGbo3x8/52wKpnAk/x6Yon5pyA74=";
  })
  (fetchNuGet {
    pname = "Avalonia.X11";
    version = "11.0.10";
    hash = "sha256-/CRivMxpcbW1FnIuwZbF2ucdcbn4TCyjKzLXgdGtCfQ=";
  })
  (fetchNuGet {
    pname = "Fody";
    version = "6.6.4";
    hash = "sha256-Xe9sGzIdQ970f0RwxD3KhdfqvGUoTpim2u2oqYHkDcI=";
  })
  (fetchNuGet {
    pname = "GitLabApiClient";
    version = "1.8.0";
    hash = "sha256-62o3vqjiY0mnrAPoMJ/3XN4PHme1cSmQVZMzGVOyhvw=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp";
    version = "7.3.0";
    hash = "sha256-LlPQO/NYgIMWicvLOtWsQzCp512QpIImYDP9/n2rDOc=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp.NativeAssets.Linux";
    version = "7.3.0";
    hash = "sha256-AEHjgqX0o+Fob0SeZ6EikGKoEe6rRxess5fVJ31UL0U=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp.NativeAssets.macOS";
    version = "7.3.0";
    hash = "sha256-6oFcdKb17UX5wyAUeCCKXGvzkf0w3MNdZOVMvs54tqw=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp.NativeAssets.WebAssembly";
    version = "7.3.0";
    hash = "sha256-9VI0xCavuuIIStuQ7ipBfWu5HrAt+Kk/F2j57C1llTU=";
  })
  (fetchNuGet {
    pname = "HarfBuzzSharp.NativeAssets.Win32";
    version = "7.3.0";
    hash = "sha256-WnB7l73hneU9Kpbm8S9zEYbZHjFre24vWz0vl8+v28M=";
  })
  (fetchNuGet {
    pname = "HtmlAgilityPack";
    version = "1.11.60";
    hash = "sha256-6nVQz5hTOJlkJq1ULaP4nGf957ITHNu5XtxV4PMO+0o=";
  })
  (fetchNuGet {
    pname = "MicroCom.Runtime";
    version = "0.11.0";
    hash = "sha256-VdwpP5fsclvNqJuppaOvwEwv2ofnAI5ZSz2V+UEdLF0=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Ref";
    version = "6.0.36";
    hash = "sha256-9jDkWbjw/nd8yqdzVTagCuqr6owJ/DUMi4BlUZT4hWU=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.linux-arm64";
    version = "6.0.36";
    hash = "sha256-JQULJyF0ivLoUU1JaFfK/HHg+/qzpN7V2RR2Cc+WlQ4=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.linux-x64";
    version = "6.0.36";
    hash = "sha256-zUsVIpV481vMLAXaLEEUpEMA9/f1HGOnvaQnaWdzlyY=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.osx-arm64";
    version = "6.0.36";
    hash = "sha256-2seqZcz0JeUjkzh3QcGa9TcJ4LUafpFjTRk+Nm8T6T0=";
  })
  (fetchNuGet {
    pname = "Microsoft.AspNetCore.App.Runtime.osx-x64";
    version = "6.0.36";
    hash = "sha256-yxLafxiBKkvfkDggPk0P9YZIHBkDJOsFTO7/V9mEHuU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Bcl.AsyncInterfaces";
    version = "6.0.0";
    hash = "sha256-49+H/iFwp+AfCICvWcqo9us4CzxApPKC37Q5Eqrw+JU=";
  })
  (fetchNuGet {
    pname = "Microsoft.Bcl.AsyncInterfaces";
    version = "7.0.0";
    hash = "sha256-1e031E26iraIqun84ad0fCIR4MJZ1hcQo4yFN+B7UfE=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Analyzers";
    version = "3.0.0";
    hash = "sha256-KDbCfsBWSJ5ohEXUKp1s1LX9xA2NPvXE/xVzj68EdC0=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Common";
    version = "3.8.0";
    hash = "sha256-3G9vSc/gHH7FWgOySLTut1+eEaf3H66qcPOvNPLOx4o=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.CSharp";
    version = "3.8.0";
    hash = "sha256-i/r3V/No/VzqmJlWxpGoirvlbJDbBPa/ONZtzYrxuc4=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.CSharp.Scripting";
    version = "3.8.0";
    hash = "sha256-fA9Qu+vTyMZ9REzxJ4aMg/SHCDRk4q9k4ZGUdynoHnA=";
  })
  (fetchNuGet {
    pname = "Microsoft.CodeAnalysis.Scripting.Common";
    version = "3.8.0";
    hash = "sha256-866jMHp8kbc1FYpKuUWnd7ViU6kGJTAxPcL/IjXrT0I=";
  })
  (fetchNuGet {
    pname = "Microsoft.CSharp";
    version = "4.3.0";
    hash = "sha256-a3dAiPaVuky0wpcHmpTVtAQJNGZ2v91/oArA+dpJgj8=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.linux-arm64";
    version = "6.0.36";
    hash = "sha256-9lC/LYnthYhjkWWz2kkFCvlA5LJOv11jdt59SDnpdy0=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.linux-x64";
    version = "6.0.36";
    hash = "sha256-VFRDzx7LJuvI5yzKdGmw/31NYVbwHWPKQvueQt5xc10=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.osx-arm64";
    version = "6.0.36";
    hash = "sha256-DaSWwYACJGolEBuMhzDVCj/rQTdDt061xCVi+gyQnuo=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Host.osx-x64";
    version = "6.0.36";
    hash = "sha256-FrRny9EI6HKCKQbu6mcLj5w4ooSRrODD4Vj2ZMGnMd4=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Ref";
    version = "6.0.36";
    hash = "sha256-9LZgVoIFF8qNyUu8kdJrYGLutMF/cL2K82HN2ywwlx8=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.linux-arm64";
    version = "6.0.36";
    hash = "sha256-k3rxvUhCEU0pVH8KgEMtkPiSOibn+nBh+0zT2xIfId8=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.linux-x64";
    version = "6.0.36";
    hash = "sha256-U8wJ2snSDFqeAgDVLXjnniidC7Cr5aJ1/h/BMSlyu0c=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.osx-arm64";
    version = "6.0.36";
    hash = "sha256-UfLcrL2Gj/OLz0s92Oo+OCJeDpZFAcQLPLiSNND8D5Y=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.App.Runtime.osx-x64";
    version = "6.0.36";
    hash = "sha256-0xIJYFzxdMcnCj3wzkFRQZSnQcPHzPHMzePRIOA3oJs=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "1.1.0";
    hash = "sha256-FeM40ktcObQJk4nMYShB61H/E8B7tIKfl9ObJ0IOcCM=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "2.1.2";
    hash = "sha256-gYQQO7zsqG+OtN4ywYQyfsiggS2zmxw4+cPXlK+FB5Q=";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Targets";
    version = "1.1.0";
    hash = "sha256-0AqQ2gMS8iNlYkrD+BxtIg7cXMnr9xZHtKAuN4bjfaQ=";
  })
  (fetchNuGet {
    pname = "Mono.Posix.NETStandard";
    version = "1.0.0";
    hash = "sha256-/F61k7MY/fu2FcfW7CkyjuUroKwlYAXPQFVeDs1QknY=";
  })
  (fetchNuGet {
    pname = "NETStandard.Library";
    version = "2.0.3";
    hash = "sha256-Prh2RPebz/s8AzHb2sPHg3Jl8s31inv9k+Qxd293ybo=";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "12.0.3";
    hash = "sha256-PSHK+Qn52ytdEySdZyjCUGxV5y4hI/vir2WgVsCgv50=";
  })
  (fetchNuGet {
    pname = "NSubsys";
    version = "1.0.0";
    hash = "sha256-feXogw550L1Yh6fGTi8bdXtn4Uq+vF0+WAn4zEptnIU=";
  })
  (fetchNuGet {
    pname = "PropertyChanged.Fody";
    version = "4.1.0";
    hash = "sha256-SAId/w7y5RZqMnpnJ6nmMjaPXQIr2h6QsRKZ4yuoYYU=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Collections";
    version = "4.3.0";
    hash = "sha256-4PGZqyWhZ6/HCTF2KddDsbmTTjxs2oW79YfkberDZS8=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Globalization";
    version = "4.3.0";
    hash = "sha256-PaiITTFI2FfPylTEk7DwzfKeiA/g/aooSU1pDcdwWLU=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.IO";
    version = "4.3.0";
    hash = "sha256-vej7ySRhyvM3pYh/ITMdC25ivSd0WLZAaIQbYj/6HVE=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection";
    version = "4.3.0";
    hash = "sha256-ns6f++lSA+bi1xXgmW1JkWFb2NaMD+w+YNTfMvyAiQk=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection.Extensions";
    version = "4.3.0";
    hash = "sha256-Y2AnhOcJwJVYv7Rp6Jz6ma0fpITFqJW+8rsw106K2X8=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Reflection.Primitives";
    version = "4.3.0";
    hash = "sha256-LkPXtiDQM3BcdYkAm5uSNOiz3uF4J45qpxn5aBiqNXQ=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Resources.ResourceManager";
    version = "4.3.0";
    hash = "sha256-9EvnmZslLgLLhJ00o5MWaPuJQlbUFcUF8itGQNVkcQ4=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime";
    version = "4.3.0";
    hash = "sha256-qwhNXBaJ1DtDkuRacgHwnZmOZ1u9q7N8j0cWOLYOELM=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime.Handles";
    version = "4.3.0";
    hash = "sha256-PQRACwnSUuxgVySO1840KvqCC9F8iI9iTzxNW0RcBS4=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Runtime.InteropServices";
    version = "4.3.0";
    hash = "sha256-Kaw5PnLYIiqWbsoF3VKJhy7pkpoGsUwn4ZDCKscbbzA=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Text.Encoding";
    version = "4.3.0";
    hash = "sha256-Q18B9q26MkWZx68exUfQT30+0PGmpFlDgaF0TnaIGCs=";
  })
  (fetchNuGet {
    pname = "runtime.any.System.Threading.Tasks";
    version = "4.3.0";
    hash = "sha256-agdOM0NXupfHbKAQzQT8XgbI9B8hVEh+a/2vqeHctg4=";
  })
  (fetchNuGet {
    pname = "runtime.debian.8-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-LXUPLX3DJxsU1Pd3UwjO1PO9NM2elNEDXeu2Mu/vNps=";
  })
  (fetchNuGet {
    pname = "runtime.fedora.23-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-qeSqaUI80+lqw5MK4vMpmO0CZaqrmYktwp6L+vQAb0I=";
  })
  (fetchNuGet {
    pname = "runtime.fedora.24-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-SrHqT9wrCBsxILWtaJgGKd6Odmxm8/Mh7Kh0CUkZVzA=";
  })
  (fetchNuGet {
    pname = "runtime.native.System";
    version = "4.3.0";
    hash = "sha256-ZBZaodnjvLXATWpXXakFgcy6P+gjhshFXmglrL5xD5Y=";
  })
  (fetchNuGet {
    pname = "runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-Jy01KhtcCl2wjMpZWH+X3fhHcVn+SyllWFY8zWlz/6I=";
  })
  (fetchNuGet {
    pname = "runtime.opensuse.13.2-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-wyv00gdlqf8ckxEdV7E+Ql9hJIoPcmYEuyeWb5Oz3mM=";
  })
  (fetchNuGet {
    pname = "runtime.opensuse.42.1-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-zi+b4sCFrA9QBiSGDD7xPV27r3iHGlV99gpyVUjRmc4=";
  })
  (fetchNuGet {
    pname = "runtime.osx.10.10-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-gybQU6mPgaWV3rBG2dbH6tT3tBq8mgze3PROdsuWnX0=";
  })
  (fetchNuGet {
    pname = "runtime.rhel.7-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-VsP72GVveWnGUvS/vjOQLv1U80H2K8nZ4fDAmI61Hm4=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.14.04-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-4yKGa/IrNCKuQ3zaDzILdNPD32bNdy6xr5gdJigyF5g=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.16.04-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-HmdJhhRsiVoOOCcUvAwdjpMRiyuSwdcgEv2j9hxi+Zc=";
  })
  (fetchNuGet {
    pname = "runtime.ubuntu.16.10-x64.runtime.native.System.Security.Cryptography.OpenSsl";
    version = "4.3.0";
    hash = "sha256-pVFUKuPPIx0edQKjzRon3zKq8zhzHEzko/lc01V/jdw=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Diagnostics.Debug";
    version = "4.3.0";
    hash = "sha256-ReoazscfbGH+R6s6jkg5sIEHWNEvjEoHtIsMbpc7+tI=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Private.Uri";
    version = "4.3.0";
    hash = "sha256-c5tXWhE/fYbJVl9rXs0uHh3pTsg44YD1dJvyOA0WoMs=";
  })
  (fetchNuGet {
    pname = "runtime.unix.System.Runtime.Extensions";
    version = "4.3.0";
    hash = "sha256-l8S9gt6dk3qYG6HYonHtdlYtBKyPb29uQ6NDjmrt3V4=";
  })
  (fetchNuGet {
    pname = "SkiaSharp";
    version = "2.88.7";
    hash = "sha256-Ip3afwTr4QOqtwOUKqK6g/9Ug4dMSebTci5K29Jc3Dg=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.Linux";
    version = "2.88.7";
    hash = "sha256-QdQRN1IBjqohmI8U+6WJRPgOsh8a9soN2UvVObs1H1w=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.macOS";
    version = "2.88.7";
    hash = "sha256-WgPldXSqPMm0TrdUWAyjge5rcRhd9G3/Ix/v/2NQvBc=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.WebAssembly";
    version = "2.88.7";
    hash = "sha256-oIjFF+Rv+g8AKyNaaVAgnHX3eeP/l8K2sgHs9bRyUMw=";
  })
  (fetchNuGet {
    pname = "SkiaSharp.NativeAssets.Win32";
    version = "2.88.7";
    hash = "sha256-+7RxCAr+ne9MZWdXKKpV4ZbHW0k6hLD20ZFWWOCiNYU=";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.4.0";
    hash = "sha256-KTxAhYawFG2V5VX1jw3pzx3IrQXRgn1TsvgjPgxAbqA=";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.5.1";
    hash = "sha256-wws90sfi9M7kuCPWkv1CEYMJtCqx9QB/kj0ymlsNaxI=";
  })
  (fetchNuGet {
    pname = "System.Collections";
    version = "4.3.0";
    hash = "sha256-afY7VUtD6w/5mYqrce8kQrvDIfS2GXDINDh73IjxJKc=";
  })
  (fetchNuGet {
    pname = "System.Collections.Immutable";
    version = "5.0.0";
    hash = "sha256-GdwSIjLMM0uVfE56VUSLVNgpW0B//oCeSFj8/hSlbM8=";
  })
  (fetchNuGet {
    pname = "System.ComponentModel.Annotations";
    version = "4.5.0";
    hash = "sha256-15yE2NoT9vmL9oGCaxHClQR1jLW1j1ef5hHMg55xRso=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.Debug";
    version = "4.3.0";
    hash = "sha256-fkA79SjPbSeiEcrbbUsb70u9B7wqbsdM9s1LnoKj0gM=";
  })
  (fetchNuGet {
    pname = "System.Diagnostics.DiagnosticSource";
    version = "7.0.2";
    hash = "sha256-8Uawe7mWOQsDzMSAAP16nuGD1FRSajyS8q+cA++MJ8E=";
  })
  (fetchNuGet {
    pname = "System.Dynamic.Runtime";
    version = "4.3.0";
    hash = "sha256-k75gjOYimIQtLBD5NDzwwi3ZMUBPRW3jmc3evDMMJbU=";
  })
  (fetchNuGet {
    pname = "System.Globalization";
    version = "4.3.0";
    hash = "sha256-caL0pRmFSEsaoeZeWN5BTQtGrAtaQPwFi8YOZPZG5rI=";
  })
  (fetchNuGet {
    pname = "System.IO";
    version = "4.3.0";
    hash = "sha256-ruynQHekFP5wPrDiVyhNiRIXeZ/I9NpjK5pU+HPDiRY=";
  })
  (fetchNuGet {
    pname = "System.IO.Pipelines";
    version = "6.0.0";
    hash = "sha256-xfjF4UqTMJpf8KsBWUyJlJkzPTOO/H5MW023yTYNQSA=";
  })
  (fetchNuGet {
    pname = "System.Linq";
    version = "4.3.0";
    hash = "sha256-R5uiSL3l6a3XrXSSL6jz+q/PcyVQzEAByiuXZNSqD/A=";
  })
  (fetchNuGet {
    pname = "System.Linq.Expressions";
    version = "4.3.0";
    hash = "sha256-+3pvhZY7rip8HCbfdULzjlC9FPZFpYoQxhkcuFm2wk8=";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.3";
    hash = "sha256-Cvl7RbRbRu9qKzeRBWjavUkseT2jhZBUWV1SPipUWFk=";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.4";
    hash = "sha256-3sCEfzO4gj5CYGctl9ZXQRRhwAraMQfse7yzKoRe65E=";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.5";
    hash = "sha256-EPQ9o1Kin7KzGI5O3U3PUQAZTItSbk9h/i4rViN3WiI=";
  })
  (fetchNuGet {
    pname = "System.Numerics.Vectors";
    version = "4.4.0";
    hash = "sha256-auXQK2flL/JpnB/rEcAcUm4vYMCYMEMiWOCAlIaqu2U=";
  })
  (fetchNuGet {
    pname = "System.Numerics.Vectors";
    version = "4.5.0";
    hash = "sha256-qdSTIFgf2htPS+YhLGjAGiLN8igCYJnCCo6r78+Q+c8=";
  })
  (fetchNuGet {
    pname = "System.ObjectModel";
    version = "4.3.0";
    hash = "sha256-gtmRkWP2Kwr3nHtDh0yYtce38z1wrGzb6fjm4v8wN6Q=";
  })
  (fetchNuGet {
    pname = "System.Private.Uri";
    version = "4.3.0";
    hash = "sha256-fVfgcoP4AVN1E5wHZbKBIOPYZ/xBeSIdsNF+bdukIRM=";
  })
  (fetchNuGet {
    pname = "System.Reactive";
    version = "6.0.0";
    hash = "sha256-hXB18OsiUHSCmRF3unAfdUEcbXVbG6/nZxcyz13oe9Y=";
  })
  (fetchNuGet {
    pname = "System.Reflection";
    version = "4.3.0";
    hash = "sha256-NQSZRpZLvtPWDlvmMIdGxcVuyUnw92ZURo0hXsEshXY=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit";
    version = "4.3.0";
    hash = "sha256-5LhkDmhy2FkSxulXR+bsTtMzdU3VyyuZzsxp7/DwyIU=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.ILGeneration";
    version = "4.3.0";
    hash = "sha256-mKRknEHNls4gkRwrEgi39B+vSaAz/Gt3IALtS98xNnA=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Emit.Lightweight";
    version = "4.3.0";
    hash = "sha256-rKx4a9yZKcajloSZHr4CKTVJ6Vjh95ni+zszPxWjh2I=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Extensions";
    version = "4.3.0";
    hash = "sha256-mMOCYzUenjd4rWIfq7zIX9PFYk/daUyF0A8l1hbydAk=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Metadata";
    version = "5.0.0";
    hash = "sha256-Wo+MiqhcP9dQ6NuFGrQTw6hpbJORFwp+TBNTq2yhGp8=";
  })
  (fetchNuGet {
    pname = "System.Reflection.Primitives";
    version = "4.3.0";
    hash = "sha256-5ogwWB4vlQTl3jjk1xjniG2ozbFIjZTL9ug0usZQuBM=";
  })
  (fetchNuGet {
    pname = "System.Reflection.TypeExtensions";
    version = "4.3.0";
    hash = "sha256-4U4/XNQAnddgQIHIJq3P2T80hN0oPdU2uCeghsDTWng=";
  })
  (fetchNuGet {
    pname = "System.Resources.ResourceManager";
    version = "4.3.0";
    hash = "sha256-idiOD93xbbrbwwSnD4mORA9RYi/D/U48eRUsn/WnWGo=";
  })
  (fetchNuGet {
    pname = "System.Runtime";
    version = "4.3.0";
    hash = "sha256-51813WXpBIsuA6fUtE5XaRQjcWdQ2/lmEokJt97u0Rg=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "4.5.3";
    hash = "sha256-lnZMUqRO4RYRUeSO8HSJ9yBHqFHLVbmenwHWkIU20ak=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "4.6.0";
    hash = "sha256-FTjQeMuvqnKxpoVsVh/OlQ21NMaZiFtOdv7VdZ+Iv3Y=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "4.7.1";
    hash = "sha256-UvyoDV8O0oY3HPG1GbA56YVdvwTGEfjYR5gW1O7IK4U=";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "6.0.0";
    hash = "sha256-bEG1PnDp7uKYz/OgLOWs3RWwQSVYm+AnPwVmAmcgp2I=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Extensions";
    version = "4.3.0";
    hash = "sha256-wLDHmozr84v1W2zYCWYxxj0FR0JDYHSVRaRuDm0bd/o=";
  })
  (fetchNuGet {
    pname = "System.Runtime.Handles";
    version = "4.3.0";
    hash = "sha256-KJ5aXoGpB56Y6+iepBkdpx/AfaJDAitx4vrkLqR7gms=";
  })
  (fetchNuGet {
    pname = "System.Runtime.InteropServices";
    version = "4.3.0";
    hash = "sha256-8sDH+WUJfCR+7e4nfpftj/+lstEiZixWUBueR2zmHgI=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding";
    version = "4.3.0";
    hash = "sha256-GctHVGLZAa/rqkBNhsBGnsiWdKyv6VDubYpGkuOkBLg=";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding.CodePages";
    version = "4.5.1";
    hash = "sha256-PIhkv59IXjyiuefdhKxS9hQfEwO9YWRuNudpo53HQfw=";
  })
  (fetchNuGet {
    pname = "System.Threading";
    version = "4.3.0";
    hash = "sha256-ZDQ3dR4pzVwmaqBg4hacZaVenQ/3yAF/uV7BXZXjiWc=";
  })
  (fetchNuGet {
    pname = "System.Threading.Channels";
    version = "6.0.0";
    hash = "sha256-klGYnsyrjvXaGeqgfnMf/dTAMNtcHY+zM4Xh6v2JfuE=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks";
    version = "4.3.0";
    hash = "sha256-Z5rXfJ1EXp3G32IKZGiZ6koMjRu0n8C1NGrwpdIen4w=";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.5.4";
    hash = "sha256-owSpY8wHlsUXn5xrfYAiu847L6fAKethlvYx97Ri1ng=";
  })
  (fetchNuGet {
    pname = "System.ValueTuple";
    version = "4.5.0";
    hash = "sha256-niH6l2fU52vAzuBlwdQMw0OEoRS/7E1w5smBFoqSaAI=";
  })
  (fetchNuGet {
    pname = "Tmds.DBus.Protocol";
    version = "0.15.0";
    hash = "sha256-4gk2vXDjKFaBh82gTkwg3c/5GRjiH+bvM5elfDSbKTU=";
  })
]
