apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-state-metrics
  namespace: cicd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./generated/nixidy/prod/kube-state-metrics
    repoURL: https://github.com/schradert/dotfiles.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - FailOnSharedResource=true
      - PruneLast=true
      - ServerSideApply=true
