apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: volsync--autobrr--autobrr-dst
  namespace: media
spec:
  restic:
    copyMethod: Direct
    destinationPVC: autobrr
    moverSecurityContext:
      runAsGroup: 101
      runAsUser: 101
    repository: volsync--autobrr--autobrr
  trigger:
    manual: "1"
