apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: dragonfly-operator
    app.kubernetes.io/instance: dragonflydb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dragonfly-operator
    app.kubernetes.io/part-of: dragonfly-operator
  name: dragonflydb-dragonfly-operator-controller-svc
  namespace: storage
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/instance: dragonflydb
    app.kubernetes.io/name: dragonfly-operator
    control-plane: controller-manager
  type: ClusterIP
