apiVersion: v1
automountServiceAccountToken: true
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dragonfly-operator
    app.kubernetes.io/instance: dragonflydb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: dragonfly-operator
    app.kubernetes.io/part-of: dragonfly-operator
  name: dragonfly-operator-controller-manager
  namespace: storage
