github_pat: ENC[AES256_GCM,data:2cFxd1efB5ILmZ2bAYl4hh4AuzduY4kvEzl3AKK0HPClsTkW6CTIjQ==,iv:tK/nqisrMHCXmKi5LZBrivFOjLuLcqFA4t32aFjD460=,tag:P29gyw18eYiRqFsbiQetkw==,type:str]
gitlab_pat: ENC[AES256_GCM,data:vhJrHOLOfn8+tHEN+dJvrgsPnwak/RB+/ks=,iv:Zf51DH1qTiHkeuSM8ibhVj3/iYTOHc2EeirBXEaewCs=,tag:rxqR0ixgYsR7aAyrzMiSBg==,type:str]
cloudflare:
    api_key: ENC[AES256_GCM,data:Z7XoB/o374odqj+hbAfgwgadcCMsq52JAcuJ7VP2hvFWxVBwHw==,iv:h+XS72YcXu2kJRge4uAG6T73mPWRKi+o97aSytX6xZY=,tag:RZ5Dcbvuy49uq1eTIokvgg==,type:str]
    pat: ENC[AES256_GCM,data:0xB2jjTizGFB4dCnEymvLDrKjNZULXuwQG4uepRlptNEa1jGn69U/w==,iv:KzBhVx5OakUIsqcdqTwPPo8XG9K3jI92zm+vWwhIMXQ=,tag:qUT0pjEtrLeZfeedfTnrgg==,type:str]
opentofu_pw: ENC[AES256_GCM,data:aa2RytQl/fgkKADVeQBLyDbTyh/nm9I+,iv:cUYcwZt8VV9dFGpNXD76i5ZBL7JySQFjZxmS092jVOk=,tag:Zwh8CXbAIaGEmEaqV6FdYA==,type:str]
trdos_ip: ENC[AES256_GCM,data:r0Az4licj1sme+VfLkY=,iv:dEf51wlEgQnujmG5IN88QrW4EheTNNR59jT2L5t5U6o=,tag:phHGZbE+KVfrDnr6QQbMHw==,type:str]
backblaze:
    application_key: ENC[AES256_GCM,data:OerPMCCqBWI2j6TaqI5yex/OaF2jlxlMjYANG9Nj66jey0J5WUxpMJI/,iv:dcbFqalGI3M55fUYwSPYBiQ88xNloEs1omNl8fX7Feg=,tag:diYfbv+EI29+/esIQuGpyg==,type:str]
    application_key_id: ENC[AES256_GCM,data:sOjG9FqxEzvChbbB,iv:kg0lwWEkQa98j85C2yA0mC+07XtYUj+OxdyxhjmdzC0=,tag:jU5LEAyD7fXaCWsQ9rIS6Q==,type:str]
bitwarden:
    id: ENC[AES256_GCM,data:6HOysrFcoxxL7v9ju7027eLB/ndQKOQu1yrDTfyVbGYuXnWM,iv:jEkQO/x8GZNKCM2+0H1iTM2zFhiV0QFPLgS0Y6YpzCk=,tag:CkWH7EYdRYEniwNcNFvlCA==,type:str]
    key: ENC[AES256_GCM,data:QDTrPmFW5LmuFHFkl0sA5McBwu0=,iv:1ZMIiV/UIwZmefua25NUJTgOX6fmtHIlVDHpIlveVOM=,tag:aT5B3aJ3t78ScZ3LT0lX+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age198yu3najdv79x087fa9qnl9x0pctugcl08ccc3cjpxd6h8ygp57sjglj0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bENUTDkvRUU2RUxNTmox
            OTBmcWpEOXNrdWJYVDAvWkROTkdxV1FxVmlnCmw4R0tNVmFNSHBrcCtXdzBBTTNL
            NnFmVDJCTjZZdzh4amw2Mk9kbkg2RlkKLS0tIEhMRW1ZUmtMbnhkSlAwOExEMEJi
            RUVzTGVCL0p0bSs5d2Jpc3p0ZldtYUkKS9vx8/HR9ZeH0GB34mCBDDhCm2XLLCWX
            VDKZ48OMnlRRAFin9X/wj6RyUJlk0AWG6wgnlsLqnxE8m0+D1U2PDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-26T23:13:52Z"
    mac: ENC[AES256_GCM,data:XdXSdpaWmmLxGQwuADbYxc4O9Zh6ZiF/N4niNO2DPyguQMc2ZJrbKld8cr6TuJvkufGJynqkWtdgb1/pFOtO10tiqqq8gmRDl/O5eQOkGN1avEPPBfUhgGubCCnXX2Gy0zEwFSeExoB8HqYSkcva30JyoanuW2SkGZIE8kCjGqs=,iv:KZAXCFuld+0Db+fS25knIrzal+Tg0/avFqz3qHvo1x0=,tag:LBtTodrEksTbCpUlWCJs3w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
