github: ENC[AES256_GCM,data:lRg2p28LHHBNWeeDSxvKQAleQCUfyY3K9/w1FEVMrRu/mIWdaeuL0g==,iv:91SIaWEMMIqGjPoTOJfKcx/DIcw1Qtn4nFgEV7wLLtA=,tag:wynucss0XkeqFGW7QrNptg==,type:str]
gitlab: ENC[AES256_GCM,data:D4hO35hY6Hpsofw3A1QH7txBaglYQAW6qPk=,iv:asfyfaSE3IV374FrvYz0d+epsxqK+3hW+1V+GLTApgo=,tag:P6YT6608HG6gLp8TylxdZQ==,type:str]
cloudflare: ENC[AES256_GCM,data:uNODwoUb5IvnLzlRe/LkfcgrKoQDNSfcrPFJ3netO19ty7KV8GNOvg==,iv:HI9dg+Vk9pehDaQX/+4SczhxLBVOqqwOBifYB7TtI3E=,tag:fq6Ztz6a0Dda6XidVt+sjQ==,type:str]
opentofu_pw: ENC[AES256_GCM,data:aa2RytQl/fgkKADVeQBLyDbTyh/nm9I+,iv:cUYcwZt8VV9dFGpNXD76i5ZBL7JySQFjZxmS092jVOk=,tag:Zwh8CXbAIaGEmEaqV6FdYA==,type:str]
backblaze: ENC[AES256_GCM,data:FSnGSbdJZMwuDCOx3pX6tS8hihdVHzUbXhnBJz6Kyg==,iv:Mu9WXuKSkUyGs2UzNPEhUBQ0Dz5P/cuiEPFQlZed+bk=,tag:QPGDCdi1uX2E5rwVVvQfWQ==,type:str]
bitwarden: ENC[AES256_GCM,data:sSao2xNrRNp6KgSDLYsdwL9jQU5IDt0d2lWc8KTwLg7UaBOFOzwpdxM8Zi2NYuSg0ZuwFruR5LGXKxu1Webqdc7vz98J77Wg7x4u5/aQiSBFMeFPTUnnCJiRGqj5rQ==,iv:sLbZJIStTz7EwDG+fqxmxaBwqB2t2h0UiRuuFZZ4Otg=,tag:sYrGLlTXbD8g4qLOEwNaWQ==,type:str]
passwords:
    k3s-token: ENC[AES256_GCM,data:wIIC71BNgiLp2z+vMUVTaHBTxOAl,iv:nKP7WxFoJEEVbCVxtsRoaRkQePTkcnUrK+Cw6rarVco=,tag:4p1d+DwZG5iGjHU6LLs3lw==,type:str]
sops:
    age:
        - recipient: age198yu3najdv79x087fa9qnl9x0pctugcl08ccc3cjpxd6h8ygp57sjglj0k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4bENUTDkvRUU2RUxNTmox
            OTBmcWpEOXNrdWJYVDAvWkROTkdxV1FxVmlnCmw4R0tNVmFNSHBrcCtXdzBBTTNL
            NnFmVDJCTjZZdzh4amw2Mk9kbkg2RlkKLS0tIEhMRW1ZUmtMbnhkSlAwOExEMEJi
            RUVzTGVCL0p0bSs5d2Jpc3p0ZldtYUkKS9vx8/HR9ZeH0GB34mCBDDhCm2XLLCWX
            VDKZ48OMnlRRAFin9X/wj6RyUJlk0AWG6wgnlsLqnxE8m0+D1U2PDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-06T04:43:03Z"
    mac: ENC[AES256_GCM,data:cfvU5WojgVR+FBO7IUsCB3FJcKXz5mu8Aus/5SW9j7mfRt8XLKJyloLoaU9q55bcZOLL++q8CScqxc79qxxwDg5f8yLP5uzdTKnj5VpsWvZ3JynUAJAp5Vi7TeC2AXSXphvqhUrEjhSFhPWOcCFHmLMBY6s+8ksmN1d8EufA6cM=,iv:zDp0pIst5CXiDteUmrE1ecpU8KvLdoPRXxXa6bvwWi8=,tag:6dfuum7+qltFWBU5YAoGMA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
