apiVersion: v1
data:
  ADMIN_TOKEN_FILE: /secrets/admin_token.txt
  DOMAIN: https://vaultwarden.trdos.me
  PGDATABASE: vaultwarden
  PGHOST: main.default.svc.cluster.local
  PGPASSWORD_FILE: /secrets/db_password.txt
  PGUSER: vaultwarden
  PUSH_ENABLED: "true"
  PUSH_INSTALLATION_ID: 41b4a972-2412-450c-8f86-b1cc01772f38
  PUSH_INSTALLATION_KEY_FILE: /secrets/installation_key.txt
  SHOW_PASSWORD_HINT: "false"
  SIGNUPS_ALLOWED: "false"
  SIGNUPS_VERIFY: "true"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vaultwarden
  name: vaultwarden
  namespace: dotfiles
