apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vaultwarden
  namespace: dotfiles
spec:
  data:
    - remoteRef:
        key: vaultwarden/admin
      secretKey: admin_token.txt
    - remoteRef:
        key: vaultwarden/installation
      secretKey: installation_key.txt
    - remoteRef:
        key: vaultwarden.main.credentials.postgresql.acid.zalan.do
        property: password
      secretKey: db_password.txt
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-default
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
