apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: vaultwarden
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vaultwarden
  name: vaultwarden
  namespace: dotfiles
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
