apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: volsync--vaultwarden--vaultwarden-dst
  namespace: dotfiles
spec:
  restic:
    copyMethod: Direct
    destinationPVC: vaultwarden
    moverSecurityContext:
      runAsGroup: 101
      runAsUser: 101
    repository: volsync--vaultwarden--vaultwarden
  trigger:
    manual: "1"
