apiVersion: v1
data:
  config.yaml: |
    connectivity:
      checker:
        interval: 1m
        target: 1.1.1.1:53
    debug: false
    endpoints:
    - client:
        dns-resolver: tcp://1.1.1.1:53
      conditions:
      - '[STATUS] == 200'
      group: external
      interval: 1m
      name: autobrr
      url: https://autobrr.trdos.me
    - client:
        dns-resolver: tcp://1.1.1.1:53
      conditions:
      - '[STATUS] == 200'
      group: external
      interval: 1m
      name: bazarr
      url: https://bazarr.trdos.me
    - client:
        dns-resolver: tcp://1.1.1.1:53
      conditions:
      - '[STATUS] == 200'
      group: external
      interval: 1m
      name: gatus
      url: https://gatus.trdos.me
    - client:
        dns-resolver: tcp://1.1.1.1:53
      conditions:
      - '[STATUS] == 200'
      group: external
      interval: 1m
      name: jellyfin
      url: https://jellyfin.trdos.me
    - client:
        dns-resolver: tcp://1.1.1.1:53
      conditions:
      - '[STATUS] == 200'
      group: external
      interval: 1m
      name: lidarr
      url: https://lidarr.trdos.me
    - client:
        dns-resolver: tcp://1.1.1.1:53
      conditions:
      - '[STATUS] == 200'
      group: external
      interval: 1m
      name: maintainerr
      url: https://maintainerr.trdos.me
    - client:
        dns-resolver: tcp://1.1.1.1:53
      conditions:
      - '[STATUS] == 200'
      group: external
      interval: 1m
      name: prowlarr
      url: https://prowlarr.trdos.me
    - client:
        dns-resolver: tcp://1.1.1.1:53
      conditions:
      - '[STATUS] == 200'
      group: external
      interval: 1m
      name: radarr
      url: https://radarr.trdos.me
    - client:
        dns-resolver: tcp://1.1.1.1:53
      conditions:
      - '[STATUS] == 200'
      group: external
      interval: 1m
      name: readarr
      url: https://readarr.trdos.me
    - client:
        dns-resolver: tcp://1.1.1.1:53
      conditions:
      - '[STATUS] == 200'
      group: external
      interval: 1m
      name: sonarr
      url: https://sonarr.trdos.me
    - client:
        dns-resolver: tcp://1.1.1.1:53
      conditions:
      - '[STATUS] == 200'
      group: external
      interval: 1m
      name: vaultwarden
      url: https://vaultwarden.trdos.me
    metrics: true
    storage:
      caching: true
      path: $GATUS_DB_URI
      type: postgres
    ui:
      header: Status
      title: Status | Gatus
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: gatus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: gatus
  name: gatus
  namespace: monitoring
