apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gatus
  namespace: gatus
spec:
  dataFrom:
    - extract:
        key: gatus.main.credentials.postgresql.acid.zalan.do
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-default
  target:
    template:
      data:
        GATUS_DB_URI: postgres://gatus:{{ .password }}@main.default.svc.cluster.local:5432/gatus
