apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: volsync--prowlarr--prowlarr-src
  namespace: dotfiles
spec:
  restic:
    copyMethod: Direct
    moverSecurityContext:
      fsGroup: 101
    pruneIntervalDays: 8
    repository: volsync--prowlarr--prowlarr
    retain:
      daily: 1
      monthly: 1
      weekly: 1
      yearly: 1
  sourcePVC: prowlarr
  trigger:
    schedule: 0 4 * * *
