apiVersion: v1
data:
  jicofo.conf: |
    # Using jicofo /default/jicofo.conf from container image
  logging.properties: |
    # Using jicofo /default/logging.properties from container image
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: jicofo
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jitsi-meet
  name: jitsi-jitsi-meet-jicofo-defaults
  namespace: dotfiles
