apiVersion: v1
data:
  custom-config.js: ""
  custom-interface_config.js: ""
  default: ""
  ffdhe2048.txt: ""
  interface_config.js: ""
  meet.conf: ""
  nginx.conf: ""
  settings-config.js: ""
  ssl.conf: ""
  system-config.js: ""
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jitsi-meet
  name: jitsi-jitsi-meet-web-conffiles
  namespace: dotfiles
