apiVersion: v1
data:
  JIBRI_BREWERY_MUC: jibribrewery
  JIBRI_PENDING_TIMEOUT: "90"
  JICOFO_ENABLE_REST: "1"
  JIGASI_BREWERY_MUC: jigasibrewery
  JIGASI_SIP_URI: available
  JVB_BREWERY_MUC: jvbbrewery
  XMPP_SERVER: jitsi-prosody.dotfiles.svc.cluster.local
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: jicofo
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jitsi-meet
  name: jitsi-jitsi-meet-jicofo
  namespace: dotfiles
