apiVersion: v1
data:
  finalize.sh: |
    # Not using a custom finalize.sh
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: jibri
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jitsi-meet
  name: jitsi-jitsi-meet-jibri-other
  namespace: dotfiles
