apiVersion: v1
data:
  JIGASI_BREWERY_MUC: jigasibrewery
  XMPP_SERVER: jitsi-prosody.dotfiles.svc.cluster.local
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: jigasi
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jitsi-meet
  name: jitsi-jitsi-meet-jigasi
  namespace: dotfiles
