apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: jicofo
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jitsi-meet
  name: jitsi-jitsi-meet-jicofo
  namespace: dotfiles
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: jicofo
      app.kubernetes.io/instance: jitsi
      app.kubernetes.io/name: jitsi-meet
  template:
    metadata:
      annotations:
        checksum/config: 1810aac00a632b587f99617d59dc87a04740a2ab490abd79fb234bcc8775fccb
        checksum/secret: e7c1c5d853de78a4c84c3e38dceffa7f42eb542b7cfeb4124424adc19d658615
      labels:
        app.kubernetes.io/component: jicofo
        app.kubernetes.io/instance: jitsi
        app.kubernetes.io/name: jitsi-meet
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: jitsi-prosody-jicofo
            - configMapRef:
                name: jitsi-prosody-common
            - configMapRef:
                name: jitsi-jitsi-meet-jicofo
          image: jitsi/jicofo:jicofo-1.0-1152-1@sha256:3830c204714ecde016cb7beb96fb1297fd58d62d40738ba56b9458471241e805
          imagePullPolicy: Never
          livenessProbe:
            tcpSocket:
              port: 8888
          name: jitsi-meet
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 8888
          resources: {}
          securityContext: {}
          volumeMounts:
            - mountPath: /config
              name: config
        - image: prayagsingh/prometheus-jicofo-exporter:1.3.2@sha256:50d4ac714856924faed7ad426be796cb00261b277fe4f723b72f9e6b18011469
          imagePullPolicy: Never
          name: metrics
          ports:
            - containerPort: 9996
              name: metrics
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 9996
            initialDelaySeconds: 3
            periodSeconds: 5
          resources: {}
      securityContext: {}
      serviceAccountName: jitsi-jitsi-meet
      volumes:
        - emptyDir: {}
          name: config
        - configMap:
            defaultMode: 493
            items:
              - key: 10-config
                path: 10-config
            name: jitsi-jitsi-meet-jicofo-cont-inits
          name: custom-cont-inits
        - configMap:
            items:
              - key: jicofo.conf
                path: jicofo.conf
              - key: logging.properties
                path: logging.properties
            name: jitsi-jitsi-meet-jicofo-defaults
          name: custom-defaults
