apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: jigasi
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jitsi-meet
  name: jitsi-jitsi-meet-jigasi
  namespace: dotfiles
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: jigasi
      app.kubernetes.io/instance: jitsi
      app.kubernetes.io/name: jitsi-meet
  template:
    metadata:
      annotations:
        checksum/config: 47740ec05f6efce41912cf4ce179bdb7ed53a9966b94b6f888bf2debf96e56cb
        checksum/secret: db0f56836a025eccaebf5adbfe465da0dd05e47bb95a88f84966c401f1babc14
      labels:
        app.kubernetes.io/component: jigasi
        app.kubernetes.io/instance: jitsi
        app.kubernetes.io/name: jitsi-meet
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: jitsi-prosody-jigasi
            - configMapRef:
                name: jitsi-prosody-common
            - configMapRef:
                name: jitsi-jitsi-meet-jigasi
          image: jitsi/jigasi:jigasi-1.1-392-g03d83b3-1@sha256:29623c814dcd4073d8920bd6f7248b2ac088bbab173799b096ad586eb245d2bc
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              httpHeaders:
                - name: Accept
                  value: application/json
              path: /about/health
              port: 8788
          name: jitsi-meet
          readinessProbe:
            httpGet:
              httpHeaders:
                - name: Accept
                  value: application/json
              path: /about/health
              port: 8788
          resources: {}
          securityContext: {}
      securityContext: {}
      serviceAccountName: jitsi-jitsi-meet
