apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jitsi-prosody-jibri
  namespace: dotfiles
spec:
  data:
    - remoteRef:
        key: jitsi/recorder
      secretKey: recorder
    - remoteRef:
        key: jitsi/jibri
      secretKey: jibri
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    template:
      data:
        JIBRI_RECORDER_PASSWORD: '{{ .recorder }}'
        JIBRI_RECORDER_USER: recorder
        JIBRI_XMPP_PASSWORD: '{{ .jibri }}'
        JIBRI_XMPP_USER: jibri
