apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jitsi-prosody-jvb
  namespace: dotfiles
spec:
  data:
    - remoteRef:
        key: jitsi/jvb
      secretKey: jvb
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    template:
      data:
        JVB_AUTH_PASSWORD: '{{ .jvb }}'
        JVB_AUTH_USER: jvb
