apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jitsi-prosody-jicofo
  namespace: dotfiles
spec:
  data:
    - remoteRef:
        key: jitsi/jicofo
      secretKey: jicofo
    - remoteRef:
        key: jitsi/component
      secretKey: component
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    template:
      data:
        JICOFO_AUTH_PASSWORD: '{{ .jicofo }}'
        JICOFO_AUTH_USER: focus
        JICOFO_COMPONENT_SECRET: '{{ .component }}'
