apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jitsi-prosody-jigasi
  namespace: dotfiles
spec:
  data:
    - remoteRef:
        key: jitsi/jigasi
      secretKey: jigasi
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    template:
      data:
        JIGASI_XMPP_PASSWORD: '{{ .jigasi }}'
        JIGASI_XMPP_USER: jigasi
