apiVersion: v1
data: {}
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: jvb
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jitsi-meet
  name: jitsi-prosody-jvb
  namespace: dotfiles
type: Opaque
