apiVersion: v1
data: {}
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: jibri
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jitsi-meet
  name: jitsi-prosody-jibri
  namespace: dotfiles
type: Opaque
