apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: jibri
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jitsi-meet
  name: jitsi-jitsi-meet-jibri
  namespace: dotfiles
spec:
  ports:
    - name: http-internal
      port: 3333
      protocol: TCP
      targetPort: 3333
    - name: http-api
      port: 2222
      protocol: TCP
      targetPort: 2222
  selector:
    app.kubernetes.io/component: jibri
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/name: jitsi-meet
  type: ClusterIP
