apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: volsync--recyclarr--recyclarr
  namespace: media
spec:
  data:
    - remoteRef:
        key: restic
      secretKey: restic
    - remoteRef:
        key: bucket
      secretKey: password
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
  target:
    template:
      data:
        AWS_ACCESS_KEY_ID: 004099163b2ee630000000002
        AWS_DEFAULT_REGION: us-west-004
        AWS_SECRET_ACCESS_KEY: '{{ .password }}'
        RESTIC_PASSWORD: '{{ .restic }}'
        RESTIC_REPOSITORY: s3:https://s3.us-west-004.backblazeb2.com/trdos-me--volsync/volsync--recyclarr--recyclarr
