apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: volsync--recyclarr--recyclarr-src
  namespace: media
spec:
  restic:
    copyMethod: Direct
    moverSecurityContext:
      fsGroup: 101
    pruneIntervalDays: 8
    repository: volsync--recyclarr--recyclarr
    retain:
      daily: 1
      monthly: 1
      weekly: 1
      yearly: 1
  sourcePVC: recyclarr
  trigger:
    schedule: 0 4 * * *
