apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: spegel
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: spegel
  name: spegel
  namespace: storage
