apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: spegel
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: spegel
  name: spegel
  namespace: storage
spec:
  ports:
    - name: metrics
      port: 9090
      protocol: TCP
      targetPort: metrics
  selector:
    app.kubernetes.io/instance: spegel
    app.kubernetes.io/name: spegel
