apiVersion: v1
data:
  oauth2_proxy.cfg: |
    code_challenge_method = "S256"
    cookie_domains = [".trdos.me"]
    cookie_secure = true
    email_domains = ["*"]
    oidc_issuer_url = "https://keycloak.trdos.me/realms/primary"
    provider = "keycloak-oidc"
    redirect_url = "https://oauth2-proxy.trdos.me/oauth2/callback"
    reverse_proxy = true
    set_xauthrequest = true
    skip_provider_button = true
    whitelist_domains = [".trdos.me"]
kind: ConfigMap
metadata:
  name: oauth2-proxy
  namespace: security
