apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oauth2-proxy
  namespace: security
spec:
  data:
    - remoteRef:
        key: oauth2-proxy/cookie
      secretKey: cookie-secret
    - remoteRef:
        key: oauth2-proxy/keycloak/client-id
      secretKey: client-id
    - remoteRef:
        key: oauth2-proxy/keycloak/client-secret
      secretKey: client-secret
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
