apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: oauth2-proxy
    app.kubernetes.io/component: authentication-proxy
    app.kubernetes.io/instance: oauth2-proxy
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/part-of: oauth2-proxy
    prometheus: default
  name: oauth2-proxy
  namespace: security
spec:
  endpoints:
    - interval: 60s
      path: /metrics
      port: metrics
      scrapeTimeout: 30s
  jobLabel: oauth2-proxy
  namespaceSelector:
    matchNames:
      - security
  selector:
    matchLabels:
      app.kubernetes.io/instance: oauth2-proxy
      app.kubernetes.io/name: oauth2-proxy
