provider = "keycloak-oidc"
provider_display_name = "Keycloak"
# TODO pass these values through a secret
# client_id = ""
# client_secret = ""
# redirect_url = "https://net.t0rdos.me/oauth2/callback"
# oidc_issuer_url = "https://key.t0rdos.me/realms/me"
# email_domains = "t0rdos.me"
# allowed_roles = ["me", "client:you"]
# allowed_groups = ["family"]
# reverse_proxy = True
# pass_basic_auth = True
# pass_user_headers = True
# prefer_email_to_user = True
# set_authorization_header = True
# set_xauthrequest = True
# skip_provider_button = True
# silence_ping_logging = True
# upstreams = ["static://202"]
# scope = "openid profile email"
