apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firefly-importer
  namespace: dotfiles
spec:
  data:
    - remoteRef:
        key: firefly/token
      secretKey: app_token.txt
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
