apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firefly
  namespace: dotfiles
spec:
  data:
    - remoteRef:
        key: firefly/key
      secretKey: app_key.txt
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: firefly.main.credentials.postgresql.acid.zalan.do
        property: password
      secretKey: db_password.txt
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-default
