apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: firefly
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: firefly
  name: firefly
  namespace: dotfiles
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
