apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: volsync
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: volsync
    control-plane: volsync-controller
  name: volsync-metrics
  namespace: storage
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    control-plane: volsync-controller
