apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin
  namespace: dotfiles
spec:
  dataFrom:
    - extract:
        key: atuin.main.credentials.postgresql.acid.zalan.do
  secretStoreRef:
    kind: ClusterSecretStore
    name: kubernetes-default
  target:
    template:
      data:
        ATUIN_DB_URI: postgres://atuin:{{ .password }}@main.default.svc.cluster.local:5432/atuin
