apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/instance: atuin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: atuin
  name: atuin
  namespace: dotfiles
spec:
  endpoints:
    - interval: 1m
      path: /metrics
      port: metrics
      scheme: http
      scrapeTimeout: 10s
  jobLabel: atuin
  namespaceSelector:
    matchNames:
      - dotfiles
  selector:
    matchLabels:
      app.kubernetes.io/instance: atuin
      app.kubernetes.io/name: atuin
      app.kubernetes.io/service: atuin
