apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: volsync--maintainerr--maintainerr-src
  namespace: dotfiles
spec:
  restic:
    copyMethod: Direct
    moverSecurityContext:
      fsGroup: 101
    pruneIntervalDays: 8
    repository: volsync--maintainerr--maintainerr
    retain:
      daily: 1
      monthly: 1
      weekly: 1
      yearly: 1
  sourcePVC: maintainerr
  trigger:
    schedule: 0 4 * * *
