apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: volsync--maintainerr--maintainerr-dst
  namespace: dotfiles
spec:
  restic:
    copyMethod: Direct
    destinationPVC: maintainerr
    moverSecurityContext:
      runAsGroup: 101
      runAsUser: 101
    repository: volsync--maintainerr--maintainerr
  trigger:
    manual: "1"
