apiVersion: v1
data:
  readme: Templates in this folder are packaged with an operator and available via 'useTemplate'
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: clickhouse
    meta.helm.sh/release-namespace: storage
  labels:
    app.kubernetes.io/instance: clickhouse
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: operator
  name: clickhouse-operator-keeper-templatesd-files
  namespace: storage
