apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clickhouse-credentials
  namespace: storage
spec:
  data:
    - remoteRef:
        key: clickhouse
      secretKey: password
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
  target:
    template:
      data:
        password: '{{ .password }}'
        user: default
