apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: volsync--clickhouse--clickhouse-logs-dst
  namespace: storage
spec:
  restic:
    copyMethod: Direct
    destinationPVC: clickhouse-logs-chi-clickhouse-clickhouse-0-0-0
    moverSecurityContext:
      runAsGroup: 101
      runAsUser: 101
    repository: volsync--clickhouse--clickhouse-logs
  trigger:
    manual: "1"
