apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: clickhouse
    meta.helm.sh/release-namespace: storage
  labels:
    app.kubernetes.io/instance: clickhouse
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: operator
  name: clickhouse-operator-metrics
  namespace: storage
spec:
  ports:
    - name: clickhouse-metrics
      port: 8888
    - name: operator-metrics
      port: 9999
  selector:
    app.kubernetes.io/instance: clickhouse
    app.kubernetes.io/name: operator
