apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: storage
  namespace: storage
spec:
  cephConfig:
    global:
      bdev_async_discard_threads: "1"
      bdev_enable_discard: "true"
      device_failure_prediction_mode: local
      osd_class_update_on_start: "false"
  cephVersion:
    allowUnsupported: false
    image: quay.io/ceph/ceph:v19.2.2
  cleanupPolicy:
    allowUninstallWithVolumes: false
    confirmation: ""
    sanitizeDisks:
      dataSource: zero
      iteration: 1
      method: quick
    wipeDevicesFromOtherClusters: true
  continueUpgradeAfterChecksEvenIfNotHealthy: false
  crashCollector:
    disable: false
  csi:
    readAffinity:
      enabled: true
  dashboard:
    enabled: true
    prometheusEndpoint: http://prometheus-operated.monitoring.svc.cluster.local:9090
    ssl: false
    urlPrefix: /
  dataDirHostPath: /var/lib/rook
  disruptionManagement:
    managePodBudgets: true
    osdMaintenanceTimeout: 30
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
      osd:
        disabled: false
        interval: 60s
      status:
        disabled: false
        interval: 60s
    livenessProbe:
      mgr:
        disabled: false
      mon:
        disabled: false
      osd:
        disabled: false
  logCollector:
    enabled: true
    maxLogSize: 500M
    periodicity: daily
  mgr:
    allowMultiplePerNode: false
    count: 2
    modules:
      - enabled: true
        name: diskprediction_local
      - enabled: true
        name: insights
      - enabled: true
        name: pg_autoscaler
      - enabled: true
        name: rook
  mon:
    allowMultiplePerNode: false
    count: 3
  monitoring:
    enabled: true
  network:
    connections:
      compression:
        enabled: false
      encryption:
        enabled: false
      requireMsgr2: true
    provider: host
  priorityClassNames:
    mgr: system-cluster-critical
    mon: system-node-critical
    osd: system-node-critical
  removeOSDsIfOutAndSafeToRemove: false
  resources:
    cleanup:
      limits:
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 100Mi
    crashcollector:
      limits:
        memory: 60Mi
      requests:
        cpu: 100m
        memory: 60Mi
    exporter:
      limits:
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 50Mi
    logcollector:
      limits:
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
    mgr:
      limits:
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 512Mi
    mgr-sidecar:
      limits:
        memory: 100Mi
      requests:
        cpu: 100m
        memory: 40Mi
    mon:
      limits:
        memory: 2Gi
      requests:
        cpu: 1000m
        memory: 1Gi
    osd:
      limits:
        memory: 4Gi
      requests:
        cpu: 1000m
        memory: 4Gi
    prepareosd:
      requests:
        cpu: 500m
        memory: 50Mi
  skipUpgradeChecks: false
  storage:
    nodes:
      - devices:
          - name: /dev/disk/by-id/scsi-35000c50067fb404b
          - name: /dev/disk/by-id/scsi-35000c50067fc5df3
          - name: /dev/disk/by-id/scsi-35000c50067fc640b
          - name: /dev/disk/by-id/scsi-35000c50067fcc0d3
          - name: /dev/disk/by-id/scsi-35000c50067fcc2fb
          - name: /dev/disk/by-id/scsi-35000c50067fcd9af
          - name: /dev/disk/by-id/scsi-35000c50067fe560f
        name: sirver
      - devices:
          - name: /dev/disk/by-id/scsi-36b82a720cf60ce002fd94d462aff700b
          - name: /dev/disk/by-id/scsi-36b82a720cf60ce002fd94d552bdede19
          - name: dev/disk/by-id/scsi-36b82a720cf60ce002fd94d622ca764e8
          - name: /dev/disk/by-id/scsi-36b82a720cf60ce002fd94d6f2d66f068
          - name: /dev/disk/by-id/scsi-36b82a720cf60ce002fd94d7c2e2ed82e
          - name: /dev/disk/by-id/scsi-36b82a720cf60ce002fd94d8a2f011f94
          - name: /dev/disk/by-id/scsi-36b82a720cf60ce002fd94d962fc2bcad
        name: octopus
    useAllDevices: false
    useAllNodes: false
  upgradeOSDRequiresHealthyPGs: false
  waitTimeoutForHealthyOSDInMinutes: 10
