apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: main
  namespace: storage
spec:
  databases:
    gatus: gatus
    keycloak: keycloak
    vaultwarden: vaultwarden
  numberOfInstances: 1
  postgresql:
    version: "16"
  teamId: acid
  users:
    gatus: createdb
    keycloak: createdb
    superadmin: superuser
    vaultwarden: createdb
  volume:
    size: 10Gi
