apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: main
  namespace: storage
spec:
  databases:
    autobrr: autobrr
    gatus: gatus
    keycloak: keycloak
    lidarr-log: lidarr
    lidarr-main: lidarr
    prowlarr-log: prowlarr
    prowlarr-main: prowlarr
    radarr-log: radarr
    radarr-main: radarr
    readarr-cache: readarr
    readarr-log: readarr
    readarr-main: readarr
    rreading-glasses: rreading-glasses
    sonarr-log: sonarr
    sonarr-main: sonarr
    vaultwarden: vaultwarden
    windmill: windmill
  numberOfInstances: 1
  postgresql:
    version: "16"
  teamId: acid
  users:
    autobrr: createdb
    gatus: createdb
    keycloak: createdb
    lidarr: createdb
    prowlarr: createdb
    radarr: createdb
    readarr: createdb
    rreading-glasses: createdb
    sonarr: createdb
    superadmin: superuser
    vaultwarden: createdb
    windmill: superuser
    windmill_admin: createdb
    windmill_user: createdb
  volume:
    size: 10Gi
