apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr
  namespace: dotfiles
spec:
  data:
    - remoteRef:
        key: radarr
      secretKey: RADARR__AUTH__APIKEY
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: radarr.main.credentials.postgresql.acid.zalan.do
        property: password
      secretKey: RADARR__POSTGRES__PASSWORD
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-default
