apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: radarr
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: radarr
  name: radarr
  namespace: dotfiles
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
