apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: volsync--radarr--radarr-dst
  namespace: dotfiles
spec:
  restic:
    copyMethod: Direct
    destinationPVC: radarr
    moverSecurityContext:
      runAsGroup: 101
      runAsUser: 101
    repository: volsync--radarr--radarr
  trigger:
    manual: "1"
