apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie
  namespace: dotfiles
spec:
  data:
    - remoteRef:
        key: mealie.main.credentials.postgresql.acid.zalan.do
        property: password
      secretKey: db_password.txt
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-default
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
