local opt = vim.opt
local g = vim.g

g.mapleader = "  "
g.maplocalleader = ","
g.ale_disable_lsp = 1
opt.ignorecase = true
opt.hidden = true
opt.history = 1000
opt.mouse = "a"
opt.number = true
opt.shiftwidth = 4
opt.smartcase = true
opt.tabstop = 4
opt.expandtab = true
opt.syntax = "enable"
opt.autoread = true
opt.cmdheight = 2
opt.updatetime = 300
opt.ruler = true
opt.foldenable = false
opt.compatible = false
opt.encoding = "utf-8"
opt.enc = "utf-8"
opt.fileencoding = "utf-8"
opt.fileencodings = "ucs-bom,utf-8"
opt.wrap = false
opt.incsearch = true
opt.showcmd = true
opt.showmatch = true
opt.showmode = true
opt.hlsearch = true
opt.scrolloff = 10
-- opt.wildignore = opt.wildignore .. ",*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.img,*.xlsx,*/tmp/*,*.so,*.swp,*.zip"
-- opt.smartindent = true
-- opt.autoindent = true
-- opt.clipboard = "unnamedplus"
-- opt.termguicolors = true
-- opt.cursorline = true
-- opt.viminfo = ""
-- opt.viminfofile = "NONE"
-- opt.ttimeoutlen = 5
