apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cert-manager
  namespace: security
spec:
  data:
    - remoteRef:
        key: cloudflare/account/token
      secretKey: credentials
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
