apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared
  namespace: kube-system
spec:
  data:
    - remoteRef:
        key: cloudflare/tunnel/token
      secretKey: token.txt
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
