apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: cloudflared
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: cloudflared
    app.kubernetes.io/service: cloudflared
  name: cloudflared
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/controller: cloudflared
    app.kubernetes.io/instance: cloudflared
    app.kubernetes.io/name: cloudflared
  type: ClusterIP
