apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app: kube-prometheus-stack-admission-create
    app.kubernetes.io/component: prometheus-operator-webhook
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-79.0.1
    heritage: Helm
    release: prometheus
  name: prometheus-kube-prometheus-admission-create
  namespace: monitoring
spec:
  template:
    metadata:
      labels:
        app: kube-prometheus-stack-admission-create
        app.kubernetes.io/component: prometheus-operator-webhook
        app.kubernetes.io/instance: prometheus
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
        app.kubernetes.io/part-of: kube-prometheus-stack
        chart: kube-prometheus-stack-79.0.1
        heritage: Helm
        release: prometheus
      name: prometheus-kube-prometheus-admission-create
    spec:
      containers:
        - args:
            - create
            - --host=prometheus-kube-prometheus-operator,prometheus-kube-prometheus-operator.monitoring.svc,prometheus-kube-prometheus-operator-webhook,prometheus-kube-prometheus-operator-webhook.monitoring.svc
            - --namespace=monitoring
            - --secret-name=prometheus-kube-prometheus-admission
          image: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v1.6.0
          imagePullPolicy: Never
          name: create
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      restartPolicy: OnFailure
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
        seccompProfile:
          type: RuntimeDefault
      serviceAccountName: prometheus-kube-prometheus-admission
  ttlSecondsAfterFinished: 60
