apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: volsync--prometheus--prometheus-src
  namespace: monitoring
spec:
  restic:
    copyMethod: Direct
    moverSecurityContext:
      fsGroup: 101
    pruneIntervalDays: 8
    repository: volsync--prometheus--prometheus
    retain:
      daily: 1
      monthly: 1
      weekly: 1
      yearly: 1
  sourcePVC: prometheus-prometheus-kube-prometheus-prometheus-db-prometheus-prometheus-kube-prometheus-prometheus-0
  trigger:
    schedule: 0 4 * * *
