apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  labels:
    app: kube-prometheus-stack-operator
    app.kubernetes.io/component: prometheus-operator-webhook
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kube-prometheus-stack-prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus-stack
    chart: kube-prometheus-stack-79.0.1
    heritage: Helm
    release: prometheus
  name: prometheus-kube-prometheus-operator-webhook
  namespace: monitoring
