apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns
  namespace: kube-system
spec:
  data:
    - remoteRef:
        key: cloudflare/account/token
      secretKey: token
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden
