apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr
  namespace: dotfiles
spec:
  data:
    - remoteRef:
        key: sonarr
      secretKey: SONARR__AUTH__APIKEY
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: bitwarden
    - remoteRef:
        key: sonarr.main.credentials.postgresql.acid.zalan.do
        property: password
      secretKey: SONARR__POSTGRES__PASSWORD
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-default
