apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: volsync--sonarr--sonarr-dst
  namespace: dotfiles
spec:
  restic:
    copyMethod: Direct
    destinationPVC: sonarr
    moverSecurityContext:
      runAsGroup: 101
      runAsUser: 101
    repository: volsync--sonarr--sonarr
  trigger:
    manual: "1"
