apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: volsync--jellyfin--jellyfin-dst
  namespace: media
spec:
  restic:
    copyMethod: Direct
    destinationPVC: jellyfin
    moverSecurityContext:
      runAsGroup: 101
      runAsUser: 101
    repository: volsync--jellyfin--jellyfin
  trigger:
    manual: "1"
