apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: volsync--lidarr--lidarr-dst
  namespace: dotfiles
spec:
  restic:
    copyMethod: Direct
    destinationPVC: lidarr
    moverSecurityContext:
      runAsGroup: 101
      runAsUser: 101
    repository: volsync--lidarr--lidarr
  trigger:
    manual: "1"
