apiVersion: v1
data:
  DB_HOSTNAME: main.default.svc.cluster.local
  DB_PASSWORD_FILE: /secrets/db_password.txt
  DB_USERNAME: immich
  IMMICH_CONFIG_FILE: /config/immich.json
  IMMICH_TELEMETRY_INCLUDE: all
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: immich-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: immich-server
  name: immich-server
  namespace: dotfiles
