apiVersion: v1
data:
  REDIS_HOSTNAME: immich-dragonfly.dotfiles.svc.cluster.local
  REDIS_PASSWORD_FILE: /secrets/cache_password.txt
  REDIS_USERNAME: dragonfly
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: immich-server
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: immich-server
  name: immich-server-immich-serer
  namespace: dotfiles
