apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-server
  namespace: dotfiles
spec:
  data:
    - remoteRef:
        key: immich.main.credentials.postgresql.acid.zalan.do
        property: password
      secretKey: db_password.txt
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: kubernetes-default
