apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: volsync--immich--immich-machine-learning-dst
  namespace: dotfiles
spec:
  restic:
    copyMethod: Direct
    destinationPVC: immich-machine-learning
    moverSecurityContext:
      runAsGroup: 101
      runAsUser: 101
    repository: volsync--immich--immich-machine-learning
  trigger:
    manual: "1"
