apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://api.bitwarden.com
      auth:
        secretRef:
          credentials:
            key: token
            name: external-secrets-bitwarden
      bitwardenServerSDKURL: https://bitwarden-sdk-server.security.svc.cluster.local:9998
      caProvider:
        key: tls.crt
        name: bitwarden-tls-certs-tls
        type: Secret
      identityURL: https://identity.bitwarden.com
      organizationID: ce96e43f-f2ce-4cd7-a36f-b30e0149eeaf
      projectID: baf88382-abda-41b2-8d0f-b30e014c2db9
