apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: repo-server
    app.kubernetes.io/instance: argod
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: argocd-cmp-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cmp-cm
  namespace: cicd
