apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: k8tz
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8tz
  name: k8tz
  namespace: kube-system
