apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: k8tz
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: k8tz
  name: k8tz
  namespace: kube-system
spec:
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: https
  selector:
    app.kubernetes.io/instance: k8tz
    app.kubernetes.io/name: k8tz
  type: ClusterIP
